### GET Test Notification
GET https://sc-dahenfeld.de/components/com_tdwapp/v9/notificationtest.php
Authorization: Basic {{authUsername}} {{authPassword}}

### GET Persons by project ID
GET https://sc-dahenfeld.de/components/com_tdwapp/v9/persons?teamId=200
Authorization: Basic {{authUsername}} {{authPassword}}